# Restaurant Data with Consumer Ratings

In [1]:
import mlcroissant as mlc
import pandas as pd

# Fetch the Croissant JSON-LD
croissant_dataset = mlc.Dataset('https://www.kaggle.com/datasets/uciml/restaurant-data-with-consumer-ratings/croissant/download')

# Check what record sets are in the dataset
record_sets = croissant_dataset.metadata.record_sets
print(record_sets)

# Fetch the records and put them in a DataFrame
record_set_df = pd.DataFrame(croissant_dataset.records(record_set=record_sets[0].uuid))
record_set_df.head()

WARNING:absl:WARNING: The JSON-LD `@context` is not standard. Refer to the official @context (e.g., from the example datasets in https://github.com/mlcommons/croissant/tree/main/datasets/1.0). The different keys are: {'samplingRate', 'isLiveDataset', 'rai', 'examples'}
WARNING:absl:Found the following 1 warning(s) during the validation:
  -  [Metadata(Restaurant Data with Consumer Ratings)] Property "http://mlcommons.org/croissant/citeAs" is recommended, but does not exist.

[RecordSet(uuid="chefmozaccepts.csv"), RecordSet(uuid="chefmozcuisine.csv"), RecordSet(uuid="chefmozhours4.csv"), RecordSet(uuid="chefmozparking.csv"), RecordSet(uuid="geoplaces2.csv"), RecordSet(uuid="rating_final.csv"), RecordSet(uuid="usercuisine.csv"), RecordSet(uuid="userpayment.csv"), RecordSet(uuid="userprofile.csv")]

Downloading https://www.kaggle.com/api/v1/datasets/download/uciml/restaurant-data-with-consumer-ratings?datasetVersionNumber=1...: 100%|██████| 38.9k/38.9k [00:00<00:00, 36.8MiB/s]

  chefmozaccepts.csv/placeID chefmozaccepts.csv/Rpayment
0                  b'135110'                     b'cash'
1                  b'135110'                     b'VISA'
2                  b'135110'      b'MasterCard-Eurocard'
3                  b'135110'         b'American_Express'
4                  b'135110'         b'bank_debit_cards'

In [4]:
print(record_sets)

[RecordSet(uuid="chefmozaccepts.csv"), RecordSet(uuid="chefmozcuisine.csv"), RecordSet(uuid="chefmozhours4.csv"), RecordSet(uuid="chefmozparking.csv"), RecordSet(uuid="geoplaces2.csv"), RecordSet(uuid="rating_final.csv"), RecordSet(uuid="usercuisine.csv"), RecordSet(uuid="userpayment.csv"), RecordSet(uuid="userprofile.csv")]

In [6]:
record_set_df = pd.DataFrame(croissant_dataset.records(record_set=record_sets[1].uuid))
record_set_df.head()

  chefmozcuisine.csv/placeID chefmozcuisine.csv/Rcuisine
0                  b'135110'                  b'Spanish'
1                  b'135109'                  b'Italian'
2                  b'135107'           b'Latin_American'
3                  b'135106'                  b'Mexican'
4                  b'135105'                b'Fast_Food'

In [8]:
record_set_df = pd.DataFrame(croissant_dataset.records(record_set=record_sets[4].uuid))
record_set_df.head()

,geoplaces2.csv/placeID,geoplaces2.csv/latitude,geoplaces2.csv/longitude,geoplaces2.csv/the_geom_meter,geoplaces2.csv/name,geoplaces2.csv/address,geoplaces2.csv/city,geoplaces2.csv/state,geoplaces2.csv/country,geoplaces2.csv/fax,...,geoplaces2.csv/alcohol,geoplaces2.csv/smoking_area,geoplaces2.csv/dress_code,geoplaces2.csv/accessibility,geoplaces2.csv/price,geoplaces2.csv/url,geoplaces2.csv/Rambience,geoplaces2.csv/franchise,geoplaces2.csv/area,geoplaces2.csv/other_services
0,b'134999',b'18.915421',b'-99.184871',b'0101000020957F000088568DE356715AC138C0A525FC...,b'Kiku Cuernavaca',b'Revolucion',b'Cuernavaca',b'Morelos',b'Mexico',b'?',...,b'No_Alcohol_Served',b'none',b'informal',b'no_accessibility',b'medium',b'kikucuernavaca.com.mx',b'familiar',True,b'closed',b'none'
1,b'132825',b'22.1473922',b'-100.983092',b'0101000020957F00001AD016568C4858C1243261274B...,b'puesto de tacos',b'esquina santos degollado y leon guzman',b's.l.p.',b's.l.p.',b'mexico',b'?',...,b'No_Alcohol_Served',b'none',b'informal',b'completely',b'low',b'?',b'familiar',True,b'open',b'none'
2,b'135106',b'22.1497088',b'-100.9760928',b'0101000020957F0000649D6F21634858C119AE9BF528...,b'El Rinc\xef\xbf\xbdn de San Francisco',b'Universidad 169',b'San Luis Potosi',b'San Luis Potosi',b'Mexico',b'?',...,b'Wine-Beer',b'only at bar',b'informal',b'partially',b'medium',b'?',b'familiar',True,b'open',b'none'
3,b'132667',b'23.7526973',b'-99.1633594',b'0101000020957F00005D67BCDDED8157C1222A2DC8D8...,b'little pizza Emilio Portes Gil',b'calle emilio portes gil',b'victoria ',b'tamaulipas',b'?',b'?',...,b'No_Alcohol_Served',b'none',b'informal',b'completely',b'low',b'?',b'familiar',True,b'closed',b'none'
4,b'132613',b'23.7529035',b'-99.165076',b'0101000020957F00008EBA2D06DC8157C194E03B7B50...,b'carnitas_mata',b'lic. Emilio portes gil',b'victoria',b'Tamaulipas',b'Mexico',b'?',...,b'No_Alcohol_Served',b'permitted',b'informal',b'completely',b'medium',b'?',b'familiar',True,b'closed',b'none'

In [9]:
import mlcroissant as mlc
import pandas as pd

# Fetch the Croissant JSON-LD
croissant_dataset = mlc.Dataset('https://www.kaggle.com/datasets/divyaraj2006/social-media-engagement/croissant/download')

# Check what record sets are in the dataset
record_sets = croissant_dataset.metadata.record_sets
print(record_sets)

# Fetch the records and put them in a DataFrame
record_set_df = pd.DataFrame(croissant_dataset.records(record_set=record_sets[0].uuid))
record_set_df.head()

WARNING:absl:WARNING: The JSON-LD `@context` is not standard. Refer to the official @context (e.g., from the example datasets in https://github.com/mlcommons/croissant/tree/main/datasets/1.0). The different keys are: {'samplingRate', 'rai', 'examples'}
WARNING:absl:Found the following 1 warning(s) during the validation:
  -  [Metadata(social media engagement)] Property "http://mlcommons.org/croissant/citeAs" is recommended, but does not exist.

[RecordSet(uuid="social_media_engagement1.csv")]

Downloading https://www.kaggle.com/api/v1/datasets/download/divyaraj2006/social-media-engagement?datasetVersionNumber=1...: 100%|█████████████| 2.09k/2.09k [00:00<00:00, 1.88MiB/s]

,social_media_engagement1.csv/post_id,social_media_engagement1.csv/platform,social_media_engagement1.csv/post_type,social_media_engagement1.csv/post_time,social_media_engagement1.csv/likes,social_media_engagement1.csv/comments,social_media_engagement1.csv/shares,social_media_engagement1.csv/post_day,social_media_engagement1.csv/sentiment_score
0,b'1',b'Facebook',b'image',2023-08-17 14:45:00,2121,474,628,b'Thursday',b'positive'
1,b'2',b'Facebook',b'carousel',2023-05-14 00:45:00,3660,432,694,b'Sunday',b'neutral'
2,b'3',b'Instagram',b'poll',2023-02-21 16:15:00,4955,408,688,b'Tuesday',b'negative'
3,b'4',b'Twitter',b'image',2023-11-16 00:45:00,1183,90,187,b'Thursday',b'negative'
4,b'5',b'Twitter',b'video',2023-05-23 00:30:00,3499,247,286,b'Tuesday',b'positive'

In [11]:
record_set_df.size

900